### ISSUE TITLE
_curses.error: setupterm: could not find terminal

### ISSUE THREAD

**Issue by findski** [mhostetter/gr-ADSB#63]
`Traceback (most recent call last):
  File "/home/dragon/PycharmProjects/usrp_ads_b/gr-adsb/examples/adsb_rx.py", line 271, in <module>
    main()
  File "/home/dragon/PycharmProjects/usrp_ads_b/gr-adsb/examples/adsb_rx.py", line 249, in main
    tb = top_block_cls()
  File "/home/dragon/PycharmProjects/usrp_ads_b/gr-adsb/examples/adsb_rx.py", line 184, in __init__
    self.adsb_decoder_0 = adsb.decoder("Extended Squitter Only", "None", "Brief")
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/adsb/decoder.py", line 292, in __init__
    self.screen = curses.initscr()
  File "/usr/lib/python3.10/curses/__init__.py", line 29, in initscr
    setupterm(term=_os.environ.get("TERM", "unknown"),
_curses.error: setupterm: could not find terminal
Exception ignored in atexit callback: <built-in function endwin>
_curses.error: must call initscr() first`

**Comment by bmurray** [comment]
Duplicate of #59
